1. Kiểm tra số dòng và cột của các bảng

In [3]:
import pandas as pd

DATA_DIR = "../../data/raw/fma_metadata/"

tracks = pd.read_csv(DATA_DIR + "tracks.csv", header=[0, 1], index_col=0, low_memory=False)
features = pd.read_csv(DATA_DIR + "features.csv", header=[0, 1, 2], index_col=0)
echonest = pd.read_csv(DATA_DIR + "echonest.csv", header=[0, 1, 2], index_col=0, low_memory=False)
genres = pd.read_csv(DATA_DIR + "genres.csv")


datasets = {
    "Tracks": tracks,
    "Features": features,
    "Echonest": echonest,
    "Genres": genres
}

data = []

for name, df in datasets.items():
    rows = df.shape[0]
    cols = df.shape[1]

    data.append([name, rows, cols])

summary = pd.DataFrame(
    data,
    columns=["Bảng", "Số bản ghi", "Số thuộc tính"]
)

display(summary)

       Bảng  Số bản ghi  Số thuộc tính
0    Tracks      106574             52
1  Features      106574            518
2  Echonest       13129            249
3    Genres         163              5

2. Check thuộc tính tiêu biểu của tracks.csv

In [6]:

display(tracks[[
    ("track", "title"),
    ("track", "duration"),
    ("track", "genre_top"),
    ("track", "genres_all"),
    ("album", "title"),
    ("artist", "name"),
    ("set", "subset")
]].head())

                    track                                        \
                    title duration genre_top         genres_all
track_id
2                    Food      168   Hip-Hop               [21]
3            Electric Ave      237   Hip-Hop               [21]
5              This World      206   Hip-Hop               [21]
10                Freeway      161       Pop               [10]
20        Spiritual Level      311       NaN  [17, 10, 76, 103]

                         album      artist     set
                         title        name  subset
track_id
2         AWOL - A Way Of Life        AWOL   small
3         AWOL - A Way Of Life        AWOL  medium
5         AWOL - A Way Of Life        AWOL   small
10           Constant Hitmaker   Kurt Vile   small
20                       Niris  Nicky Cook   large

3. Check thuộc tính tiêu biểu của features.csv

In [8]:

display(features[[
    "mfcc",
    "chroma_cens",
    "spectral_centroid",
    "spectral_contrast",
    "tonnetz",
    "zcr"
]].head())


selected_features = []

for group in [
    "mfcc",
    "chroma_cens",
    "spectral_centroid",
    "spectral_contrast",
    "tonnetz",
    "zcr"
]:
    # Lấy một cột đại diện trong mỗi nhóm
    col = features[group].columns[0]
    selected_features.append((group, *col))

display(features[selected_features].head())

feature          mfcc                                                    \
statistics   kurtosis
number             01        02        03        04        05        06
track_id
2            3.856789  1.541901  0.000816  0.330728  0.118731 -0.342687
3            4.296755  1.399977  0.112535 -0.211170  0.032953 -0.023489
5            2.624517  2.415293  0.440233 -0.782131 -0.771069 -0.724216
10           5.076893  1.161854  2.095651  1.372743 -0.203574 -0.345354
20          11.880132  4.085320  0.002655  1.518562  0.181947  0.339014

feature                                             ...   tonnetz            \
statistics                                          ...       std
number            07        08        09        10  ...        04        05
track_id                                            ...
2          -0.259252  0.146735  0.410656 -0.162872  ...  0.054125  0.012226
3           0.150404  0.046454  0.033484 -0.064596  ...  0.063831  0.014212
5           0.090260  0.152119  0.261731 -0.608905  ...  0.040730  0.012691
10         -0.529139  0.561974  0.281350 -0.150672  ...  0.074358  0.017952
20          0.367611  0.069932 -0.016032  0.026012  ...  0.095003  0.022492

feature                     zcr                                          \
statistics             kurtosis       max      mean    median       min
number            06         01        01        01        01        01
track_id
2           0.012111   5.758890  0.459473  0.085629  0.071289  0.000000
3           0.017740   2.824694  0.466309  0.084578  0.063965  0.000000
5           0.014759   6.808415  0.375000  0.053114  0.041504  0.000000
10          0.013921  21.434212  0.452148  0.077515  0.071777  0.000000
20          0.021355  16.669037  0.469727  0.047225  0.040039  0.000977

feature
statistics      skew       std
number            01        01
track_id
2           2.089872  0.061448
3           1.716724  0.069330
5           2.193303  0.044861
10          3.542325  0.040800
20          3.189831  0.030993

[5 rows x 329 columns]

feature,mfcc,chroma_cens,spectral_centroid,spectral_contrast,tonnetz,zcr
statistics,kurtosis,kurtosis,kurtosis,kurtosis,kurtosis,kurtosis
number,01,01,01,01,01,01
track_id,,,,,,
2,3.856789,7.180653,2.406808,2.270822,2.303301,5.758890
3,4.296755,1.888963,3.519866,3.208793,2.003829,2.824694
5,2.624517,0.527563,1.322586,1.478091,10.772251,6.808415
10,5.076893,3.702245,9.729688,2.236757,0.500884,21.434212
20,11.880132,-0.193837,2.177669,2.262174,1.112185,16.669037

4. Check thuộc tính tiêu biểu của genres.csv

In [9]:

display(genres[[
    "genre_id",
    "title",
    "parent",
    "top_level",
    "#tracks"
]].head(10))

   genre_id                title  parent  top_level  #tracks
0         1          Avant-Garde      38         38     8693
1         2        International       0          2     5271
2         3                Blues       0          3     1752
3         4                 Jazz       0          4     4126
4         5            Classical       0          5     4106
5         6              Novelty      38         38      914
6         7               Comedy      20         20      217
7         8  Old-Time / Historic       0          8      868
8         9              Country       0          9     1987
9        10                  Pop       0         10    13845