In [ ]:

import pandas as pd

raw = pd.read_csv("../data/raw/fma_metadata/raw_genres.csv")
genres = pd.read_csv("../data/raw/fma_metadata/genres.csv")
echonest = pd.read_csv("../data/raw/fma_metadata/echonest.csv")
features = pd.read_csv("../data/raw/fma_metadata/features.csv")
tracks = pd.read_csv("../data/raw/fma_metadata/tracks.csv")

display(raw.head())
display(genres.head())
display(echonest.head())
display(features.head())
display(tracks.head())

Raw: (164, 5)
Processed: (163, 5)
_merge
both          163
left_only       1
right_only      0
Name: count, dtype: int64
title_match  parent_match
True         True            159
             False             4
False        False             1
Name: count, dtype: int64
Raw: (164, 5)
Processed: (163, 5)

   genre_id genre_color   genre_handle  genre_parent_id    genre_title
0         1     #006666    Avant-Garde             38.0    Avant-Garde
1         2     #CC3300  International              NaN  International
2         3     #000099          Blues              NaN          Blues
3         4     #990099           Jazz              NaN           Jazz
4         5     #8A8A65      Classical              NaN      Classical

   genre_id  #tracks  parent          title  top_level
0         1     8693      38    Avant-Garde         38
1         2     5271       0  International          2
2         3     1752       0          Blues          3
3         4     4126       0           Jazz          4
4         5     4106       0      Classical          5